Ext.define('Fast.model.products.ProductModel', {
    extend: 'Ext.data.Model',
	fields: [
	     {name: 'id', type: 'number'},
	     {name: 'mgmtGrp', type: 'string'},
	     {name: 'itemCategory', type: 'string'},
	     {name: 'categoryName', type: 'string'},
	     {name: 'codeNumber', type: 'string'},
	     {name: 'configuration', type: 'string'},
	     {name: 'shipDate', type: 'date'},
	     {name: 'itemCode', type: 'string'},
         {name: 'itemName', type: 'string'},
         {name: 'productCode', type: 'string'},
         {name: 'productCode2', type: 'string'},
         {name: 'itemSeries', type: 'string'},
         {name: 'countryOrigin', type: 'string'},
         {name: 'inTransitDays', type: 'string'},
         {name: 'embargoPrdate', type: 'date'},
         {name: 'tarriffNum', type: 'string'},
         {name: 'comments', type: 'text'},//dalton
         {name: 'margin', type: 'number'},
         {name: 'msrp', type: 'string'},
         {name: 'dealerNet', type: 'string'},
         {name: 'productLength', type: 'string'},
         {name: 'productWidth', type: 'string'},
         {name: 'productDepth', type: 'string'},
         {name: 'productKg', type: 'string'},
         {name: 'productLbs', type: 'string'},
         {name: 'productUpc', type: 'string'},
         {name: 'boxLength', type: 'string'},
         {name: 'boxWidth', type: 'string'},
         {name: 'boxDepth', type: 'string'},
         {name: 'boxKg', type: 'string'},
         {name: 'boxLbs', type: 'string'},
         {name: 'boxUpc', type: 'string'},
         {name: 'innerLength', type: 'string'},
         {name: 'innerWidth', type: 'string'},
         {name: 'innerDepth', type: 'string'},
         {name: 'innerKg', type: 'string'},
         {name: 'innerLbs', type: 'string'},
         {name: 'innerUpc', type: 'string'},
         {name: 'masterLength', type: 'string'},
         {name: 'masterWidth', type: 'string'},
         {name: 'masterDepth', type: 'string'},
         {name: 'masterKg', type: 'string'},
         {name: 'masterLbs', type: 'string'},
         {name: 'masterUpc', type: 'string'},
         {name: 'masterQty', type: 'string'},
         {name: 'palletLayers', type: 'string'},
         {name: 'palletUnits', type: 'string'},
         {name: 'palletUpc', type: 'string'},
	     {name: 'status', type: 'string'},
	     {name: 'merchandiseType', type: 'string'}
     ]
});